---
- hosts: all

  user: deploy
#  sudo: yes
#  sudo_user: root
#  vars:
#    - rbenv_root: /usr/local/rbenv
#    - ruby_version: 2.0.0-p195

  tasks:
    - name: install dependeces
      sudo: true
      apt: pkg={{ item }}
      with_items:
        - libssl-dev
#         - build-essential
#         - bison
#         - openssl
#         - libreadline6
#         - libreadline6-dev
#         - curl
#         - git-core
#         - zlib1g
#         - zlib1g-dev
#         - libssl-dev
#         - libyaml-dev
#         - libxml2-dev
#         - autoconf
#         - libc6-dev
#         - ncurses-dev
#         - automake
#         - libtool

#    - name: Install rbenv
#      git: repo=https://github.com/sstephenson/rbenv.git
#           dest=~/.rbenv
#
#
#    - name: hook rbenv to profile
#      lineinfile: dest=~/.bashrc
#                  state=present
#                  regexp='\.rbenv/bin'
#                  line='export PATH="$HOME/.rbenv/bin:$PATH"'
#
#    - name: hook rbenv shims
#      lineinfile: dest=~/.bashrc
#                  state=present
#                  regexp='rbenv init'
#                  line='eval "$(rbenv init -)"'
#
#
#    - name: install ruby-build
#      git: repo=https://github.com/sstephenson/ruby-build.git
#           dest=~/.rbenv/plugins/ruby-build

    - name: install rubies
      shell: /home/$ansible_user_id/.rbenv/bin/rbenv install {{item}}
      with_items:
        - 2.0.0-p195