---
- name: install dependences
  sudo: yes
  apt: pkg={{ item }}
  with_items:
    - libssl-dev
    - build-essential
    - bison
    - openssl
    - libreadline6
    - libreadline6-dev
    - curl
    - git-core
    - zlib1g
    - zlib1g-dev
    - libssl-dev
    - libyaml-dev
    - libxml2-dev
    - autoconf
    - libc6-dev
#    - ncurses-dev
    - automake
    - libtool
